name: 'Aqua Tracee'
description: 'Protect your GitHub Actions pipelines with eBPF profiling'
author: 'Aqua Security'
inputs:
  envs:
    description: 'include environment variables in executable profile'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      ls
      docker pull aquasec/tracee:latest
      docker run -d --name tracee --rm -p 3366:3366 \
      --privileged --pid=host --cgroupns=host \
      -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host \
      -v /proc:/proc \
      -v /boot:/boot \
      -v /lib/modules/:/lib/modules/:ro \
      -v /etc/os-release:/etc/os-release-host:ro \
      -v /tmp/tracee/:/tmp/tracee \
      -v /usr/src:/usr/src:ro \
      -v ./config.yaml:/tracee/config.yaml \
      aquasec/tracee:latest \
      --config config.yaml \
      --output json:/tmp/tracee/out/trace.json
      echo -n "Waiting for Tracee to start..."
      while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3366/healthz)" != "200" ]]
      do
          echo -n "Still waiting..."
          sleep 1
      done
      sleep 1
      echo "Tracee started." #newline
