name: 'Aqua Tracee'
description: 'Protect your GitHub Actions pipelines with eBPF profiling'
author: 'Aqua Security'
inputs:
  fail-on-diff:
    description: "Fails the action if profile deviation found"
    required: false
    default: 'false'
  create-pr:
    description: "Creates a PR to the default branch with profile differences if found"
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo "Stopping Tracee..."
      docker stop tracee
  - name: Upload build log as artifact
    uses: actions/upload-artifact@v4
    with:
      name: build-log
      path: /tmp/tracee/out/trace.json
