blob-perf-buffer-size: 1024
cache:
    type: none
    # size: 1024

capture:
  #- write
  #- exec
  #- network

policy:
  - /path/to/policy.yaml
  #- /path/to/policy-directory

proctree:
    source: none
    # cache:
    #     process: 8192
    #     thread: 4096

capabilities:
    bypass: false
    # add:
    #     - cap_sys_admin
    #     - cap_syslog
    # drop:
    #     - cap_chown

metrics-endpoint: true

grpc-listen-addr: tcp:50051

cri:
    # - runtime:
    #     name: containerd
    #     socket: /var/run/containerd/containerd.sock
    # - runtime:
    #     name: docker
    #     socket: /var/run/docker.sock

events:
  - open
  - execve
  - accept
  - accept4
  - access
  - acct
  - add_key
  - adjtimex
  - afs
  - afs_syscall
  - alarm
  - arch_prctl
  - bdflush
  - bind
  - bpf
  - break
  - brk
  - capget
  - capset
  - chdir
  - chmod
  - chown
  - chown16
  - chroot
  - clock_adjtime
  - clock_adjtime64
  - clock_getres
  - clock_getres_time32
  - clock_gettime
  - clock_gettime32
  - clock_nanosleep
  - clock_nanosleep_time32
  - clock_settime
  - clock_settime32
  - clone
  - clone3
  - close
  - close_range
  - connect
  - copy_file_range
  - creat
  - create_module
  - delete_module
  - dup
  - dup2
  - dup3
  - epoll_create
  - epoll_create1
  - epoll_ctl
  - epoll_ctl_old
  - epoll_pwait
  - epoll_pwait2
  - epoll_wait
  - epoll_wait_old
  - eventfd
  - eventfd2
  - execve
  - execveat
  - exit
  - exit_group
  - faccessat
  - faccessat2
  - fadvise64
  - fadvise64_64
  - fallocate
  - fanotify_init
  - fanotify_mark
  - fchdir
  - fchmod
  - fchmodat
  - fchown
  - fchown16
  - fchownat
  - fcntl
  - fcntl64
  - fdatasync
  - fgetxattr
  - finit_module
  - flistxattr
  - flock
  - fork
  - fremovexattr
  - fsconfig
  - fsetxattr
  - fsmount
  - fsopen
  - fspick
  - fstat
  - fstat64
  - fstatfs
  - fstatfs64
  - fsync
  - ftime
  - ftruncate
  - ftruncate64
  - futex
  - futex_time32
  - futimesat
  - get_kernel_syms
  - get_mempolicy
  - get_robust_list
  - get_thread_area
  - getcpu
  - getcwd
  - getdents
  - getdents64
  - getegid
  - getegid16
  - geteuid
  - geteuid16
  - getgid
  - getgid16
  - getgroups
  - getgroups16
  - getitimer
  - getpeername
  - getpgid
  - getpgrp
  - getpid
  - getpmsg
  - getppid
  - getpriority
  - getrandom
  - getresgid
  - getresgid16
  - getresuid
  - getresuid16
  - getrlimit
  - getrusage
  - getsid
  - getsockname
  - getsockopt
  - gettid
  - gettimeofday
  - getuid
  - getuid16
  - getxattr
  - gtty
  - idle
  - init_module
  - inotify_add_watch
  - inotify_init
  - inotify_init1
  - inotify_rm_watch
  - io_cancel
  - io_destroy
  - io_getevents
  - io_pgetevents
  - io_pgetevents_time32
  - io_setup
  - io_submit
  - io_uring_enter
  - io_uring_register
  - io_uring_setup
  - ioctl
  - ioperm
  - iopl
  - ioprio_get
  - ioprio_set
  - ipc
  - kcmp
  - kexec_file_load
  - kexec_load
  - keyctl
  - kill
  - landlock_add_rule
  - landlock_create_ruleset
  - landlock_restrict_self
  - lchown
  - lchown16
  - lgetxattr
  - link
  - linkat
  - listen
  - listxattr
  - llistxattr
  - llseek
  - lock
  - lookup_dcookie
  - lremovexattr
  - lseek
  - lsetxattr
  - lstat
  - lstat64
  - madvise
  - mbind
  - membarrier
  - memfd_create
  - memfd_secret
  - migrate_pages
  - mincore
  - mkdir
  - mkdirat
  - mknod
  - mknodat
  - mlock
  - mlock2
  - mlockall
  - mmap
  - mmap2
  - modify_ldt
  - mount
  - mount_setattr
  - move_mount
  - move_pages
  - mprotect
  - mpx
  - mq_getsetattr
  - mq_notify
  - mq_open
  - mq_timedreceive
  - mq_timedreceive_time32
  - mq_timedsend
  - mq_timedsend_time32
  - mq_unlink
  - mremap
  - msgctl
  - msgget
  - msgrcv
  - msgsnd
  - msync
  - munlock
  - munlockall
  - munmap
  - name_to_handle_at
  - nanosleep
  - newfstatat
  - nfsservctl
  - nice
  - old_getrlimit
  - old_select
  - oldfstat
  - oldlstat
  - oldolduname
  - oldstat
  - olduname
  - open
  - open_by_handle_at
  - open_tree
  - openat
  - openat2
  - pause
  - perf_event_open
  - personality
  - pidfd_getfd
  - pidfd_open
  - pidfd_send_signal
  - pipe
  - pipe2
  - pivot_root
  - pkey_alloc
  - pkey_free
  - pkey_mprotect
  - poll
  - ppoll
  - ppoll_time32
  - prctl
  - pread64
  - preadv
  - preadv2
  - prlimit64
  - process_madvise
  - process_mrelease
  - process_vm_readv
  - process_vm_writev
  - prof
  - profil
  - pselect6
  - pselect6_time32
  - ptrace
  - putpmsg
  - pwrite64
  - pwritev
  - pwritev2
  - query_module
  - quotactl
  - quotactl_fd
  - read
  - readahead
  - readdir
  - readlink
  - readlinkat
  - readv
  - reboot
  - recvfrom
  - recvmmsg
  - recvmmsg_time32
  - recvmsg
  - remap_file_pages
  - removexattr
  - rename
  - renameat
  - renameat2
  - request_key
  - restart_syscall
  - rmdir
  - rseq
  - rt_sigaction
  - rt_sigpending
  - rt_sigprocmask
  - rt_sigqueueinfo
  - rt_sigreturn
  - rt_sigsuspend
  - rt_sigtimedwait
  - rt_sigtimedwait_time32
  - rt_tgsigqueueinfo
  - sched_get_priority_max
  - sched_get_priority_min
  - sched_getaffinity
  - sched_getattr
  - sched_getparam
  - sched_getscheduler
  - sched_rr_get_interval
  - sched_rr_get_interval_time32
  - sched_setaffinity
  - sched_setattr
  - sched_setparam
  - sched_setscheduler
  - sched_yield
  - seccomp
  - security
  - select
  - semctl
  - semget
  - semop
  - semtimedop
  - sendfile
  - sendfile32
  - sendmmsg
  - sendmsg
  - sendto
  - set_mempolicy
  - set_robust_list
  - set_thread_area
  - set_tid_address
  - setdomainname
  - setfsgid
  - setfsgid16
  - setfsuid
  - setfsuid16
  - setgid
  - setgid16
  - setgroups
  - setgroups16
  - sethostname
  - setitimer
  - setns
  - setpgid
  - setpriority
  - setregid
  - setregid16
  - setresgid
  - setresgid16
  - setresuid
  - setresuid16
  - setreuid
  - setreuid16
  - setrlimit
  - setsid
  - setsockopt
  - settimeofday
  - setuid
  - setuid16
  - setxattr
  - sgetmask
  - shmat
  - shmctl
  - shmdt
  - shmget
  - shutdown
  - sigaction
  - sigaltstack
  - signal
  - signalfd
  - signalfd4
  - sigpending
  - sigprocmask
  - sigreturn
  - sigsuspend
  - socket
  - socketcall
  - socketpair
  - splice
  - ssetmask
  - stat
  - stat64
  - statfs
  - statfs64
  - statx
  - stime
  - stty
  - swapoff
  - swapon
  - symlink
  - symlinkat
  - sync
  - sync_file_range
  - syncfs
  - sysctl
  - sysfs
  - sysinfo
  - syslog
  - tee
  - tgkill
  - time
  - timer_create
  - timer_delete
  - timer_getoverrun
  - timer_gettime
  - timer_gettime32
  - timer_settime
  - timer_settime32
  - timerfd_create
  - timerfd_gettime
  - timerfd_gettime32
  - timerfd_settime
  - timerfd_settime32
  - times
  - tkill
  - truncate
  - truncate64
  - tuxcall
  - ulimit
  - umask
  - umount
  - umount2
  - uname
  - unlink
  - unlinkat
  - unshare
  - uselib
  - userfaultfd
  - ustat
  - utime
  - utimensat
  - utimensat_time32
  - utimes
  - vfork
  - vhangup
  - vm86
  - vm86old
  - vmsplice
  - vserver
  - wait4
  - waitid
  - waitpid
  - write
  - writev

no-containers: true

healthz: true 

install-path: /tmp/tracee

listen-addr: :3366

log:
    level: info
    # file: "/path/to/log/file.log"
    # aggregate:
    #     enabled: true
    #     flush-interval: "5s"
    # filters:
    #     libbpf: false
    #     in:
    #     msg:
    #         - SampleMessage1
    #         - SampleMessage2
    #     pkg:
    #         - package1
    #         - package2
    #     file:
    #         - file1.go
    #         - file2.go
    #     level:
    #         - warn
    #         - error
    #     regex:
    #         - ^pattern1
    #         - ^pattern2
    #     out:
    #     msg:
    #         - ExcludedMessage1
    #     pkg:
    #         - excludedPackage
    #     file:
    #         - excludedFile.go
    #     level:
    #         - debug
    #     regex:
    #         - ^excludedPattern

scope:  
  #- uid=1000
  #- global
  #- pid=1000
  #- mntns=4026531840
  #- pidns=4026531836    
  #- uts=ab356bc4dd554
  #- comm=uname
  #- container
  #- not-container
  #- tree=1000
  #- executable=/usr/bin/dig
  #- follow

metrics: false

output:
    json:
        files:
            - stdout

    # table:
    #     files:
    #         - /path/to/table1.out
    #         - /path/to/table2.out

    # table-verbose:
    #     files:
    #         - stdout

    # gotemplate:
    #     template: /path/to/my_template1.tmpl
    #     files:
    #         - /path/to/output1.out
    #         - /path/to/output2.out

    # forward:
    #     - forward1:
    #         protocol: tcp
    #         user: user
    #         password: pass
    #         host: 127.0.0.1
    #         port: 24224
    #         tag: tracee1
    #     - forward2:
    #         protocol: udp
    #         user: user
    #         password: pass
    #         host: 127.0.0.1
    #         port: 24225
    #         tag: tracee2

    # webhook:
    #     - webhook1:
    #         protocol: http
    #         host: localhost
    #         port: 8000
    #         timeout: 5s
    #         gotemplate: /path/to/template/test.tmpl
    #         content-type: application/json
    #     - webhook2:
    #         protocol: http
    #         host: localhost
    #         port: 9000
    #         timeout: 3s
    #         gotemplate: /path/to/template/test.tmpl
    #         content-type: application/json

    # options:
    #     none: false
    #     stack-addresses: true
    #     exec-env: false
    #     exec-hash: dev-inode
    #     parse-arguments: true
    #     sort-events: false

perf-buffer-size: 1024

pprof: false

pyroscope: false

rego:
    # partial-eval: true
    # aio: true

signatures-dir: ""
